# ... 

[lints.rust]
keyword_idents = "warn"
non_ascii_idents = "warn"
noop_method_call = "warn"
future_incompatible = "warn"

[lints.clippy]
self_named_module_files = "warn"
cognitive_complexity = "warn"
empty_line_after_outer_attr = "warn"
empty_structs_with_brackets = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
float_equality_without_abs = "warn"
option_if_let_else = "warn"
semicolon_if_nothing_returned = "warn"
separated_literal_suffix = "warn"
shadow_unrelated = "warn"
similar_names = "warn"
suspicious_operation_groupings = "warn"
unused_self = "warn"
used_underscore_binding = "warn"
useless_let_if_seq = "warn"
wildcard_dependencies = "warn"
wildcard_imports = "warn"
dbg_macro = "warn"
char_lit_as_u8 = "warn"
checked_conversions = "warn"
empty_enum = "warn"
enum_glob_use = "warn"
exit = "warn"
inefficient_to_string = "warn"
lossy_float_literal = "warn"
mem_forget = "warn"
mut_mut = "warn"
mutex_integer = "warn"
needless_continue = "warn"
ptr_as_ptr = "warn"
rest_pat_in_fully_bound_structs = "warn"
same_functions_in_if_condition = "warn"
single_match_else = "warn"
string_lit_as_bytes = "warn"
string_to_string = "warn"
todo = "warn"
unimplemented = "warn"
unnested_or_patterns = "warn"
verbose_file_reads = "warn"
zero_sized_map_values = "warn"
debug_assert_with_mut_call = "warn"
doc_link_with_quotes = "warn"
